{% set name = "atom" %}
{% set version = "0.9.0" %}
{% set sha256 = "eccc1ab0cc1c6d1ed5b6ecd1e768f8b8727447605bd009a2a0b49b4ee7eb963d" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cppy
  run:
    - python

test:
  imports:
    - atom
    - atom.datastructures

about:
  home: https://github.com/nucleic/atom
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Memory efficient Python objects

extra:
  recipe-maintainers:
    - blink1073
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
