{% set name = "atom" %}
{% set version = "0.4.1" %}
{% set sha256 = "bbca07d519defbf0d6066a725285a9b30cb8bbf7c880f602f062b83189929f2b" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - future

test:
  imports:
    - atom
    - atom.datastructures

about:
  home: https://github.com/nucleic/atom
  license: BSD 3-Clause
  summary: Memory efficient Python objects

extra:
  recipe-maintainers:
    - blink1073
    - ericdill
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
