{% set version = "0.4.0" %}
package:
  name: atom
  version: {{ version }}

source:
  url: https://github.com/nucleic/atom/archive/{{ version }}.tar.gz
  fn: atom-{{ version }}.tar.gz
  sha256: 0ad1c86c9d3cbca8489b386287ba2274591bff818a2944ffae8ed1af420e29ee

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - future

  run:
    - python
    - future

test:
  imports:
    - atom
    - atom.datastructures

about:
  home: https://github.com/nucleic/atom
  license: BSD 3-Clause
  summary: Memory efficient Python objects

extra:
  recipe-maintainers:
    - blink1073
    - ericdill
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
