appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: AttL27xMQ/jX+Gp8MCMQpfaejBK3AmPrrAsKxgk8XCHBlBNvmepuO17+bxOxroWVQcaT02zjxSbc5voDoSMyqPsOBUKEvN9YcNBBLVO7bxsNfUudh8UEXnCvR3Cilre75bOTf92QepP0/Z9hIxTj3slsBqwLbVsJtWC6QJDbxoXDEWdhC3QoweVbrDshtK1h3eH8Z1MxGKAz3TUNv2x/CYxsfhPxo4Mup6C71aT3VZ96xruKPFTkFgggr40BtJ1re4N8D4kA/dzbBLJ7UFWqG0WtDXSAt5t3PhOpaBdja9bWQ0pThAM/5YHCPTC9EoFPuFIdM8/uy9X+g32QtMJq7tRlr+4sQS3dM2wLycsPCRpTagOVR15W++w4LlijfG/Lu2dJodTD0K3QMoP+6Qre2PZGjn5YuPgw1FX+lA0cd+7xQeIjL2oT/oGobSJjWNXghICtjrNzNCKPGIDXFKG1nWbPeb4jrz8wvWy38z6ep8HfNF07bY4OFnvgGUTg9w5E8bOmjwQ5sXBEE2Q60grSwIP4PdISVnj/lHjdVSiHgzdVQ5hg0o/CNZVPMnSigCe5g/f8QqDsdXLY6uV/W5aQ2Wr8w9FJmecrpcrrzQ1CqjLvkE5Y1Gsf2rx6ZUCD2XYKhDzB3pmWePfXjoWJKtCHecXXU1fHkm7YZT2GIACTVTg=}
provider:
  win: azure
conda_forge_output_validation: true
